name: sep_exam
description: "A new Flutter project."
version: 1.0.0+1
environment:
  sdk: ^3.5.0







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: any
  dio: ^5.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^4.0.0





flutter:

  
  uses-material-design: true

flutter_intl:
  enabled: true
  main_locale: en
  arb_dir: lib/src/common/l10n
  output_dir: lib/src/common/l10n/generated
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
